---
- hosts: ws
  become: yes
  gather_facts: 1
  ignore_errors: yes
  vars:
    f_name: John
  tasks:
    - name: Debug module
      debug:
        var: f_name

    - name: check server uptime
      command: uptime
      register: uptime_output

    - name: Display output
      debug:
        var: uptime_output.stdout_lines